### ISSUE TITLE
'@stencila/logga' dependency not satisfied via `yarn add -D @stencila/dockta` 

### ISSUE THREAD

**Issue by sixman9** [stencila/dockta#136]
Please note, the following *can* be resolved manually, simply, with `yarn add -D @stencila/logga.

Immediately after install of `yarn add -D @stencila/dockta` and issuing `npx dockta` I'm seeing:

```
Error: Cannot find module '@stencila/logga'
Require stack:
- /private/tmp/docktaPOC/my-app/node_modules/@stencila/dockta/dist/index.js
- /private/tmp/docktaPOC/my-app/node_modules/@stencila/dockta/dist/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/private/tmp/docktaPOC/my-app/node_modules/@stencila/dockta/dist/index.js:19:28)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/tmp/docktaPOC/my-app/node_modules/@stencila/dockta/dist/index.js',
    '/private/tmp/docktaPOC/my-app/node_modules/@stencila/dockta/dist/cli.js'
  ]
}
```

I thought I'd mention this (unfortunately I have another issue to submit which may or may not be related).

**Comment by nokome** [comment]
Thanks for reporting this @sixman9. I believe https://github.com/stencila/dockta/commit/e8949317d91ca77f67beed0608b761f9515b7c42 should fix it but please let me know if it doesn't.
